//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
using AuthoritativeInstructionXMLSerialization.ConsignmentService;

/// <remarks/>
 
[System.SerializableAttribute()]
 
 
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://gpcopsschema.azurewebsites.net/schema/2015/1.0/ConsignmentService")]
public partial class AuthoritativeInstructionActionUpdate
{
    /// <remarks/>
    public UpdateType Instruction { get; set; }

    /// <remarks/>
    public CoalMetadataType CoalMetadata { get; set; }

    /// <remarks/>
    public CommentType UpdateComment { get; set; }
}
